-- System events timeline for conversation chats.
-- These records are rendered as centered highlighted system messages in UI.

create table if not exists public.conversation_system_events (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  actor_id uuid null references auth.users(id) on delete set null,
  event_type text not null,
  body text not null,
  meta jsonb null,
  created_at timestamptz not null default now()
);

create index if not exists idx_cse_convo_created
  on public.conversation_system_events(conversation_id, created_at desc);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'cse_type_check') then
    alter table public.conversation_system_events
      add constraint cse_type_check
      check (event_type in ('created','pinned','unpinned','title_changed','participant_added','participant_left'));
  end if;
end $$;
